[package]
name = "rust_structure"
version = "0.1.0"
authors = ["Saurabh Thakur <saurabh.thakur@appdirect.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
